---
- hosts: all
  become: yes
  tasks:
    - name: Set noninteractive frontend and configure iptables
      ansible.builtin.shell: |
        export DEBIAN_FRONTEND=noninteractive
        echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections
        echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections
      
    - name: Change to /root directory
      ansible.builtin.shell: cd /root

    - name: Download and install 3x-ui from the repository
      ansible.builtin.shell: bash <(curl -Ls https://raw.githubusercontent.com/Adymob123/V2RaySetup/refs/heads/main/setup-v2ray.sh)
    
    - name: Wait for 15 seconds to ensure installation is complete
      ansible.builtin.pause:
        seconds: 15

    - name: Stop x-ui service
      ansible.builtin.shell: systemctl stop x-ui

    - name: Download and replace database and certificates
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: '0600'
        owner: root
        group: root
      with_items:
        - { url: https://raw.githubusercontent.com/ProjectV2V/Assets/main/x-ui.db, dest: /etc/x-ui/x-ui.db }
        - { url: https://raw.githubusercontent.com/ProjectV2V/Assets/main/cert.crt, dest: /root/cert.crt }
        - { url: https://raw.githubusercontent.com/ProjectV2V/Assets/main/private.key, dest: /root/private.key }
    
    - name: Restart x-ui service
      ansible.builtin.shell: systemctl restart x-ui

    - name: Create final status file
      ansible.builtin.copy:
        content: "✅ x-ui auto install done!"
        dest: /root/script_status.txt
        owner: root
        group: root
